language: node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache
  - yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
before_script:
  - yarn global add gulp-cli
script:
  - yarn run start