language: node_js
dist: trusty
sudo: required
node_js:
  - "node"
cache: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
before_script:
  - yarn global add gulp-cli
script:
  - yarn run start